version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    image: wordpress:latest
    volumes:
      - '$PWD/dist:/var/www/html'
    depends_on:
      - db
    ports:
      - '9000:80'
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: wordpress

  webpack:
    build: ./
    volumes:
      - './src:/src'
      - './dist:/dist'
      - './package.json:/package.json'
      - './webpack.config.js:/webpack.config.js'
    ports:
      - 2000:2000

volumes:
  db_data: {}
